HMP-ZD/Controllers/Ledger/PopupMainController.cs
using HMP_ZD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMP_ZD.Controllers.Admin.Ledger
{
    public class PopupMainController : Controller
    {
        // GET: PopupMain
        public ActionResult Index()
        {
            var db = new HMPZDDB();

            // データ一式。JOINさせる
            
            return PartialView("~/Views/Shared/Ledger/Info_popup_Main.cshtml");
        }
    }
}

HMP-ZD/Controllers/Ledger/TopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMP_ZD.Models;
using HMP_ZD.Utils;
namespace HMP_ZD.Controllers.Ledger
{
    public class TopController : Controller
    {
        // GET: Top
        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {            
            return View("~/Views/Ledger/Top.cshtml");
        }

        /// <summary>
        /// データロード
        /// </summary>
        /// <returns></returns>
        

        [HttpPost]
        public ActionResult New(string param)
        {
            return null;
        }

        /// <summary>
        /// データ入力
        /// </summary>
        private void SetData()
        {
            using(HMPZDDB db = new HMPZDDB())
            {
                #region DropDownList items
                //  確度
                ViewBag.StopItems = db.Accuracy.Where(d => d.DeleteFlg != DBUtil.FLAG_YES)
                                               .OrderBy(d => d.Order)
                                               .Select(d => new SelectListItem()
                                               {
                                                   Value = d.ID.ToString(),
                                                   Text = d.AccuracyName,
                                               })
                                               .ToList();

                //  広告種類
                ViewBag.AdvertisementTypes = db.AdvertisementTypes.Where(d => d.DeleteFlg != DBUtil.FLAG_YES)
                                                                  .OrderBy(d => d.Order)
                                                                  .Select(d => new SelectListItem()
                                                                  {
                                                                      Value = d.ID.ToString(),
                                                                      Text = d.AdvertisementType,
                                                                  })
                                                                  .ToList();
                //  画
                ViewBag.PictureItems = db.Pictures.Where(d => d.DeleteFlg != DBUtil.FLAG_YES)
                                                  .OrderBy(d => d.Order)
                                                  .Select(d => new SelectListItem()
                                                  {
                                                      Value = d.ID.ToString(),
                                                      Text = d.Picture,
                                                  })
                                                  .ToList();
                //  色
                ViewBag.ColorItems = db.Colors.Where(d => d.DeleteFlg != DBUtil.FLAG_YES)
                                              .OrderBy(d => d.Order)
                                              .Select(d => new SelectListItem()
                                              {
                                                  Value = d.ID.ToString(),
                                                  Text = d.Color,
                                              })
                                              .ToList();
                //  ページ
                ViewBag.PageItems = db.Pages.Where(d => d.DeleteFlg != DBUtil.FLAG_YES)
                                            .OrderBy(d => d.Order)
                                            .Select(d => new SelectListItem()
                                            {
                                                Value = d.ID.ToString(),
                                                Text = d.Page,
                                            })
                                            .ToList();

                //  送稿形態
                ViewBag.TransmissionFormItems = db.TransmissionForms.Where(d => d.DeleteFlg != DBUtil.FLAG_YES)
                                                                    .OrderBy(d => d.Order)
                                                                    .Select(d => new SelectListItem()
                                                                    {
                                                                        Value = d.ID.ToString(),
                                                                        Text = d.TransmissionForm,
                                                                    })
                                                                    .ToList();

                ViewBag.DepartmentItems = new List<SelectListItem>();
                ViewBag.ChargeTeamItems = new List<SelectListItem>();
                ViewBag.CustomerIDItems = new List<SelectListItem>();
                ViewBag.VehicleIDItems = new List<SelectListItem>();
                #endregion

                #region Popup data
                //  ユーザ選択の会社DropDown
                ViewBag.CompanyItems = db.Organizations.Where(d => d.DeleteFlg != DBUtil.FLAG_YES &&
                                                                   d.Hierarchy == 1)
                                                       .ToList()
                                                       .OrderBy(d => int.Parse(d.ID))
                                                       .Select(d => new SelectListItem()
                                                       {
                                                           Value = d.ComapnyCode,
                                                           Text = d.CompanyName,
                                                       })
                                                       .ToList();
                #endregion
            }
        }

        /// <summary>
        /// チーム別表示対応
        /// </summary>
        /// <param name="header"></param>
        /// <param name="data"></param>
        private void GridDataForTeam(out object[] header, out object[] data)
        {
            header =
                new[] {
new { name = "Fld1", title = "HEN受付"},
new { name = "Fld2", title = "媒体社申込"},
new { name = "Fld3", title = "担当T"},
new { name = "Fld4", title = "担当部"},
new { name = "Fld5", title = "発売月"},
new { name = "Fld6", title = "発売日"},
new { name = "Fld7", title = "掲載開始日"},
new { name = "Fld8", title = "掲載終了日"},
new { name = "Fld9", title = "媒体社"},
new { name = "Fld10", title = "媒体誌"},
new { name = "Fld11", title = "iメディア媒体社"},
new { name = "Fld12", title = "広告主"},
new { name = "Fld13", title = "件名"},
new { name = "Fld14", title = "純広告：面"},
new { name = "Fld15", title = "純広告：色"},
new { name = "Fld16", title = "純広告：P"},
new { name = "Fld17", title = "TU：面"},
new { name = "Fld18", title = "TU：色"},
new { name = "Fld19", title = "TU：P"},
new { name = "Fld20", title = "仕様"},
new { name = "Fld21", title = "媒体社"},
new { name = "Fld22", title = "納品日"},
new { name = "Fld23", title = "掲載料(G)"},
new { name = "Fld24", title = "掲載料(料率)"},
new { name = "Fld25", title = "掲載料(N)"},
new { name = "Fld26", title = "制作費(G)"},
new { name = "Fld27", title = "制作費(料率)"},
new { name = "Fld28", title = "制作費(N)"},
new { name = "Fld29", title = "媒体収益（N)"},
new { name = "Fld30", title = "引渡建値(G)"},
new { name = "Fld31", title = "戦略原価B(N)"},
new { name = "Fld32", title = "媒体支払額(N)"},
new { name = "Fld33", title = "原価項目"},
new { name = "Fld34", title = "売上金額"},
new { name = "Fld35", title = "支払原価計"},
new { name = "Fld36", title = "営収額"},
new { name = "Fld37", title = "営収率"},
new { name = "Fld38", title = "作成者"},
new { name = "Fld39", title = "作成日"},
new { name = "Fld40", title = "更新日"},

                };

            var list = new List<object>();

            // ダミーデータ            
            for (int i = 1; i <= 1007; i++)
            {
                list.Add(new
                {
                    id = i,
                    Fld1 = "ABCD1" + i,
                    Fld2 = "ABCD2" + i,
                    Fld3 = "ABCD3" + i,
                    Fld4 = "ABCD4" + i,
                    Fld5 = "ABCD5" + i,
                    Fld6 = "ABCD6" + i,
                    Fld7 = "ABCD7" + i,
                    Fld8 = "ABCD8" + i,
                    Fld9 = "ABCD9" + i,
                    Fld10 = "ABCD10" + i,
                    Fld11 = "ABCD11" + i,
                    Fld12 = "ABCD12" + i,
                    Fld13 = "ABCD13" + i,
                    Fld14 = "ABCD14" + i,
                    Fld15 = "ABCD15" + i,
                    Fld16 = "ABCD16" + i,
                    Fld17 = "ABCD17" + i,
                    Fld18 = "ABCD18" + i,
                    Fld19 = "ABCD19" + i,
                    Fld20 = "ABCD20" + i,
                    Fld21 = "ABCD21" + i,
                    Fld22 = "ABCD22" + i,
                    Fld23 = "ABCD23" + i,
                    Fld24 = "ABCD24" + i,
                    Fld25 = "ABCD25" + i,
                    Fld26 = "ABCD26" + i,
                    Fld27 = "ABCD27" + i,
                    Fld28 = "ABCD28" + i,
                    Fld29 = "ABCD29" + i,
                    Fld30 = "ABCD30" + i,
                    Fld31 = "ABCD31" + i,
                    Fld32 = "ABCD32" + i,
                    Fld33 = "ABCD33" + i,
                    Fld34 = "ABCD34" + i,
                    Fld35 = "ABCD35" + i,
                    Fld36 = "ABCD36" + i,
                    Fld37 = "ABCD37" + i,
                    Fld38 = "ABCD38" + i,
                    Fld39 = "ABCD39" + i,
                    Fld40 = "ABCD40" + i,
                    Fld41 = "ABCD41" + i,
                    Fld42 = "ABCD42" + i,
                    Fld43 = "ABCD43" + i,
                    Fld44 = "ABCD44" + i,
                    Fld45 = "ABCD45" + i,
                    Fld46 = "ABCD46" + i,
                    Fld47 = "ABCD47" + i,
                    Fld48 = "ABCD48" + i,
                    Fld49 = "ABCD49" + i,
                    Fld50 = "ABCD50" + i,

HMP-ZD/Views/Shared/Ledger/HeaderNew.cshtml
<script type="text/javascript">
$(function(){
	$(".overlay").click(function() {
        val = $(this).attr("data-href");
		$("#overlay-content").load(val);
		return false;
	});
		
	$(".other-text").hide();
	$(".other").click(function () {
		$(this).next(".other-text").slideDown("fast");
    });

    $('.setUser').on('click', function () {
        $(this).parent().find('.user').val('@ViewBag.UserName');

        var now = new Date();
        var mmdd = now.getFullYear() + '/' + 
                   ('0' + (now.getMonth() + 1)).slice(-2) + '/' + 
                   ('0' + now.getDate()).slice(-2);
        $(this).parent().find('.datepicker').val(mmdd);
    });
});
</script>
<div class="box-info01">
	<dl class="w-full">
		<dt class="pt-30">ステータス</dt>
		<dd>
			<ul class="btn-status-list">
				<li><a href="#">起票</a>
                    @if(ViewBag.ActionType == ActionType.New)
                    {
                        <span>@(DateTime.Now.ToString("yyyy/MM/dd"))</span><br />
                        <span>@ViewBag.UserName</span>
                    }
                    else if(ViewBag.ActionType == ActionType.Edit)
                    {
                        <span>@ViewBag.IssuanceStatus</span><br />
                        <span>@ViewBag.IssuanceUser</span>
                    }
                </li>
				<li><a class="setUser" href="javascript:void(0);">HEN受付</a><span>@Html.TextBox("ReportDate", (string)ViewBag.ReportDate, new { @class="datepicker w-120" })<br />@Html.TextBox("ReportUser", (string)ViewBag.ReportUser, new { @class="user", placeholder = "担当者を入力" })</span></li>
				<li><a class="setUser" href="javascript:void(0);">BA受注</a><span>@Html.TextBox("BAOrderDate", (string)ViewBag.BAOrderDate, new { @class = "datepicker w-120" })<br />@Html.TextBox("BAOrderUser", (string)ViewBag.BAOrderUser, new { @class = "user", placeholder = "担当者を入力" })</span></li>
				<li><a class="setUser" href="javascript:void(0);">媒体社申込</a><span>@Html.TextBox("CustomerApplicationDate", (string)ViewBag.CustomerApplicationDate, new { @class = "datepicker w-120" })<br />@Html.TextBox("CustomerApplicationUser", (string)ViewBag.CustomerApplicationUser, new { @class = "user", placeholder = "担当者を入力" })</span></li>
				<li><a class="setUser" href="javascript:void(0);">送稿担当者受付</a><span>@Html.TextBox("SubmitReceptDate", (string)ViewBag.SubmitReceptDate, new { @class = "datepicker w-120" })<br />@Html.TextBox("SubmitReceptUser", (string)ViewBag.SubmitReceptUser, new { @class = "user", placeholder = "担当者を入力" })</span></li>
				<li><a href="#">発注メール</a><span>@ViewBag.MailDate<br />@ViewBag.MailUser</span></li>
				<li class="ml-20"><a href="#" class="pe-none">ステータス</a>
                    @Html.DropDownList("Stop", (List<SelectListItem>)ViewBag.StopItems, "選択してください")
				</li>
			</ul>
		</dd>
	</dl>
</div>
<div class="box-info02">
	<dl>
		<dt>伝票番号</dt>
		<dd>
			<span>0000000000</span>&nbsp;<button class="ml-40">自分を担当者に設定</button>
		</dd>
		<dt>部署</dt>
		<dd>
            @Html.DropDownList("Department", (List<SelectListItem>)ViewBag.DepartmentItems, "選択してください")
		</dd>
		<dt>担当チーム</dt>
		<dd>
            @Html.DropDownList("ChargeTeam", (List<SelectListItem>)ViewBag.ChargeTeamItems, "選択してください")
		</dd>
		<dt>媒体社</dt>
		<dd>
            @Html.DropDownList("CustomerID", (List<SelectListItem>)ViewBag.CustomerIDItems, "選択してください")
			<a href="#"  class="other ml-10">その他</a>
			<div class="other-text" >
                @Html.TextBox("CustomerFree", (string)ViewBag.CustomerFree, new { @class="mt-5 w-300" })
			</div>
		</dd>
		<dt>媒体誌</dt>
		<dd>
            @Html.DropDownList("VehicleID", (List<SelectListItem>)ViewBag.VehicleIDItems, "選択してください")
			<a href="#"  class="other ml-10">その他</a>
			<div class="other-text" >
                @Html.TextBox("VehicleFree", (string)ViewBag.VehicleFree, new { @class="mt-5 w-300" })
			</div>
		</dd>
		<dt>発売日</dt>
		<dd>
            @Html.TextBox("ReleaseDate", (string)ViewBag.ReleaseDate, new { @class="datepicker" })
		</dd>
	</dl>
	<dl>
		<dt>広告主</dt>
		<dd>
			<button class="overlay mr-10" data-href="../../Popup/Ledger/ad_company.html">選択</button><span id="company">○○○○社</span>
		</dd>
		<dt>業種（大）</dt>
		<dd>
			流通・小売
		</dd>
		<dt>件名</dt>
		<dd>
            @Html.TextBox("Subject", (string)ViewBag.Subject)
		</dd>
	</dl>
</div>
<div class="box-info02">
	<dl>
		<dt>営業担当者</dt>
		<dd>
			<div class="dsp-t">
				<div class="dsp-tc w-60"><button class="overlay" data-href="../../Popup/Ledger/user.html">選択</button></div>
				<div class="dsp-tc">
                    <span id="hoge">ageee</span>
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
				</div>
			</div>
		</dd>
		<dt>雑誌部担当者</dt>
		<dd>
			<div class="dsp-t">
				<div class="dsp-tc w-60"><button class="overlay" data-href="../../Popup/Ledger/user.html">選択</button></div>
				<div class="dsp-tc">
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
				</div>
			</div>
		</dd>
	</dl>
	<dl>
		<dt>制作担当者</dt>
		<dd>
			<div class="dsp-t">
				<div class="dsp-tc w-60"><button class="overlay" data-href="../../Popup/Ledger/user.html">選択</button></div>
				<div class="dsp-tc">
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
				</div>
			</div>
		</dd>
		<dt>進行部担当者</dt>
		<dd>
			<div class="dsp-t">
				<div class="dsp-tc w-60"><button class="overlay" data-href="../../Popup/Ledger/user.html">選択</button></div>
				<div class="dsp-tc">
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
					会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
				</div>
			</div>
		</dd>
	</dl>
</div>
<div class="box-info02">
	<dl class="w-full">
		<dt></dt>
		<dd>
			<div class="dsp-t">
                @foreach(var item in (List<SelectListItem>)ViewBag.AdvertisementTypes)
                {
    				<div class="dsp-tc w-120">
                        <label><input type="checkbox"value="@item.Value" />@item.Text</label>
                    </div>
                    <div class="dsp-tc w-160">
                        画：
                        @Html.DropDownList("Pic", (List<SelectListItem>)ViewBag.PictureItems, new { })
                    </div>
                    <div class="dsp-tc w-160">
                        色：
                        @Html.DropDownList("Col", (List<SelectListItem>)ViewBag.ColorItems)
                    </div>
                    <div class="dsp-tc w-200">
                        ページ：
                        @Html.DropDownList("Pag", (List<SelectListItem>)ViewBag.PageItems)
                    </div>

                    if(item.Text == "純広告")
                    {
                        <label>電子マガジン<input type="checkbox" /></label>
                    }
                }
			</div>
		</dd>
	</dl>
</div>
<div id="overlay-content">
</div>

HMP-ZD/Views/Shared/Ledger/Info_popup_Main.cshtml
<script type="text/javascript">
$(function(){
	//Overlay
	$("#overlay,.mdl-btn-close,.mdl-btn-cancel").on("click", function() {
		$("#overlay").remove();
		$(".mdl").remove();
	});
});
</script>
<div id="overlay"></div>
<div class="mdl w-960">
    <div class="mdl-btn-close"><a href="#"><i class="fa fa-fw fa-close"></i></a></div>
    <div class="mdl-content">
        <h2 class="cl-ci-600">システムメンテナンスのお知らせ</h2>
        <div class="mb-40">
            <p class="p-5 bg-ci-50 pb-20">
                システムメンテナンスの為、下記の日程は電子台帳システムをご利用いただくことができません。<br>
                <br>
                <strong class="cl-ci-600">・2018年 3月31日 17:00～21:00</strong>
            </p>
        </div>
        <h2 class="mb-0">お知らせ</h2>
        <ul class="ta-r">
            <li><a class="btn-st btn-normal" href="@Url.Action("Index", "Top")">一覧</a></li>
        </ul>
        <div class="mt-10 box-scroll">
            <p class="p-5">
                こちらは新電子台帳システムになります。<br>
                旧電子台帳システムとは以下の点が異なっていますのでご注意ください。<br>
                <br>
                ・テキストテキストテキストテキストテキストテキストテキスト<br>
                ・テキストテキストテキストテキスト<br>
                ・テキストテキストテキストテキストテキストテキスト<br>
                ・テキストテキストテキストテキストテキスト<br>
            </p>
        </div>
    </div>
    <div class="ta-c pt-20"><a class="btn-ok btn-normal mdl-btn-cancel">了解</a></div>
</div>

HMP-ZD/Views/Shared/Ledger/MailNew.cshtml
<script type="text/javascript">
$(function(){
	$(".overlay").click(function() {
		val = $(this).attr("data-href");
		$("#overlay-content").load(val);
		return false;
	});
		
	$(".other-text").hide();
	$(".other").click(function () {
		$(this).next(".other-text").slideDown("fast");
	});
});
</script>
<h2 class="ttl-h2 tgl-btn">メール送信先一覧</h2>
<div class="tgl-box">
	<table class="tbl w-full">
		<colgroup>
			<col style="width:200px;">
			<col style="width:auto;">
			<col style="width:auto;">
			<col style="width:60px;">
		</colgroup>
		<tr>
			<th>ユーザ名</th>
			<th>部署</th>
			<th>メールアドレス</th>
			<th></th>
		</tr>
		<tr>
			<td>白鳳&#12288;太郎</td>
			<td>博報堂DYMP雑誌局業務推進二部</td>
			<td><a href="mailto:tarou.hakuho@hakuhoudody-holdings.co.jp">tarou.hakuho@hakuhoudody-holdings.co.jp</a></td>
			<td class="ta-c"><a class="btn-hk btn-small" href="#">削除</a></td>
		</tr>
		<tr>
			<td>×××××××</td>
			<td>×××××××</td>
			<td></td>
			<td class="ta-c"><a class="btn-hk btn-small" href="#">削除</a></td>
		</tr>
		<tr>
			<td>×××××××</td>
			<td>×××××××</td>
			<td></td>
			<td class="ta-c"><a class="btn-hk btn-small" href="#">削除</a></td>
		</tr>
	</table>
	<div class="mt-10"><a href="#" data-href="../../Popup/Ledger/user.html" class="overlay"><i class="fa fa-lg fa-fw fa-plus"></i>送信先メールアドレス追加</a></div>
</div>
<div id="overlay-content">
</div>

HMP-ZD/Views/Shared/Ledger/NoteNew.cshtml
<h2 class="ttl-h2 tgl-btn">備考欄</h2>
<div class="tgl-box">
	@Html.TextArea("Memo", (string)ViewBag.Memo, 10, 1, new { @class="w-full" })
</div>

HMP-ZD/Views/Shared/Ledger/PermissionNew.cshtml
<h2 class="ttl-h2 tgl-btn">アクセス権一覧</h2>
<div class="tgl-box box-scroll">
	<table class="tbl w-full">
		<colgroup>
			<col style="width:200px;">
			<col style="width:auto;">
			<col style="width:auto;">
			<col style="width:120px;">
		</colgroup>
		<tr>
			<th>ユーザ名</th>
			<th>部署</th>
			<th>メールアドレス</th>
			<th>権限</th>
		</tr>
		<tr>
			<td>白鳳&#12288;太郎</td>
			<td>博報堂DYMP雑誌局業務推進二部</td>
			<td><a href="mailto:tarou.hakuho@hakuhoudody-holdings.co.jp">tarou.hakuho@hakuhoudody-holdings.co.jp</a></td>
			<td>雑誌1部<br>雑誌2部<br>雑誌3部<br>業務推進部<br>雑誌進行部<br>局長席<br></td>
		</tr>
		<tr>
			<td>×××××××</td>
			<td>×××××××</td>
			<td></td>
			<td>局長席<br>管理者<br></td>
		</tr>
	</table>
</div>

HMP-ZD/Views/Shared/Ledger/Soukou.cshtml
<div id="Show_Soukou" hidden>
    <div class="mdl w-960">
        <div class="mdl-btn-close" id="exit_soukou"><a style="color:#c04543"><i class="fa fa-fw fa-close"></i></a></div>
        <table class="tbl w-full mt-30">
            <colgroup>
                <col style="width:150px;">
                <col style="width:auto;">
                <col style="width:150px;">
                <col style="width:auto;">
            </colgroup>
            <tr>
                <th>作成日</th>
                <td><p id="text_id"> yyyy/mm/dd</p></td>
            </tr>
            <tr>
                <th>送稿担当者</th>
                <td><p id="text_department">○○○○</p></td>
            </tr>
            <tr>
                <th>得媒体社</th>
                <td><p id="text_team">○○○○○○○○</p></td>
            </tr>
            <tr>
                <th>媒体名</th>
                <td><p id="text_user">○○○○○○○○</p></td>
            </tr>
            <tr>
                <th>発売日</th>
                <td>yyyy/mm/dd</td>
            </tr>
            <tr>
                <th>BA</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>部署</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>担当者</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>クライアント</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>件名</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>制作製版会社</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>新原稿/在版</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>原稿形態</th>
                <td>○○○○○○○○</td>
            </tr>
            <tr>
                <th>原稿返却日</th>
                <td>yyyy/mm/dd</td>
            </tr>
            <tr>
                <th>校了日</th>
                <td>yyyy/mm/dd</td>
            </tr>
            <tr>
                <th>備考</th>
                <td>○○○○○○○○○○○○○○○○<br>○○○○○○○○<br>○○○○○○</td>
            </tr>
        </table>
    </div>

</div>

HMP-ZD/Views/Shared/Ledger/UpdateNew.cshtml
<h2 class="ttl-h2 tgl-btn">更新情報メール</h2>
<div class="tgl-box mb-20">
	<div class="mt-5 mb-5">
		<h3><label><input type="checkbox" />更新情報をメールで知らせる</label></h3>
	</div>
	<table class="tbl w-full">
		<colgroup>
			<col style="width:150px;">
		</colgroup>
		<tr><th class="ta-l">送信先</th>
			<td>
				<button class="overlay" data-href="user_popup.html">選択</button><br>
				会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
				会社名 部門グループ 部門 部署 ユーザー名 <a href="#"><i class="fa fa-lg fa-fw fa-times"></i></a><br>
			</td>
		</tr>
		<tr><th class="ta-l">タイトル</th><td><input type="text" class="w-600"></td></tr>
		<tr><th class="ta-l">本文</th><td><textarea placeholder="メール本文に追加するコメントを入力してください" class="w-600"></textarea></td></tr>
	</table>
</div>
<div class="mt-20">
	<span class="cl-ok-700"><i class="fa fa-lg fa-fw fa-exclamation-circle"></i>関係者にメールが送信されます</span><br>
</div>