HMP-ZD/Controllers/Ledger/MagazineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HMP_ZD.Models;
using HMP_ZD.Utils;
using Codeplex.Data;
using System.Text;
using System.IO;

namespace HMP_ZD.Controllers.Ledger
{
    public class MagazineController : Controller
    {
        // GET: Magazine
        /// <summary>
        /// 新規作成
        /// </summary>
        /// <returns></returns>
        public ActionResult New()
        {
            //  ユーザ情報取得
            UserInfo user = new UserInfo();

            ViewBag.UserName = user.UserName;
            ViewBag.UserID = user.UserID;
            ViewBag.ActionType = ActionType.New;

            SetBaseData();

            return View("~/Views/Ledger/Magazine/New.cshtml");
        }

        /// <summary>
        /// 編集画面
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Edit(int? id)
        {
            if(!id.HasValue)
            {
                //  EditはIDが必須
                return View();
            }

            ViewBag.ActionType = ActionType.Edit;

            SetData(id.Value);
            SetBaseData();

            return View("/Views/Ledger/Magazine/Edit.cshtml");
        }

        /// <summary>
        /// 詳細画面
        /// </summary>
        /// <param name="id">台帳ID</param>
        /// <returns></returns>
        public ActionResult Detail(int? id)
        {
            if(!id.HasValue)
            {
                //  DetailはIDが必須
                return View();
            }

            ViewBag.ActionType = ActionType.Detail;

            SetData(id.Value);

            return View("/Views/Ledger/Magazine/Detail.cshtml");
        }

        /// <summary>
        /// 台帳削除
        /// </summary>
        /// <param name="id">台帳ID</param>
        /// <returns></returns>
        #region Delete
        public ActionResult DeleteLedger(int? id)
        {
            int result;

            if(!id.HasValue)
            {
                var ret = new
                {
                    Date = DateTime.Now.ToString("s"),
                    Result = false,
                    Reason = "電子台帳IDが指定されていません",
                };

                return Json(ret, JsonRequestBehavior.AllowGet);
            }

            using(HMPZDDB db = new HMPZDDB())
            {
                //  台帳データ取得
                var ledger = db.ElectronLedger.FirstOrDefault(d => d.ID == id.Value);

                if(ledger == null)
                {
                    var ret = new
                    {
                        Date = DateTime.Now.ToString("s"),
                        Result = false,
                        Reason = "指定されたIDは存在しませんでした",
                    };

                    return Json(ret, JsonRequestBehavior.AllowGet);
                }

                DBUtil.DeleteData(ref ledger);

                //  その他データ
                var sale = db.SaleRepresentatives.Where(d => d.ElectronLedgerID == id.Value).ToArray();

                for(int i = 0; i < sale.Count(); i++)
                {
                    DBUtil.DeleteData(ref sale[i]);
                }

                var mag = db.MagazineRepresentatives.Where(d => d.ElectronLedgerID == id.Value).ToArray();

                for(int i = 0; i < mag.Count(); i++)
                {
                    DBUtil.DeleteData(ref mag[i]);
                }

                var prod = db.ProductionRepresentatives.Where(d => d.ElectronLedgerID == id.Value).ToArray();

                for(int i = 0; i < prod.Count(); i++)
                {
                    DBUtil.DeleteData(ref prod[i]);
                }

                var prog = db.ProgressRepresentatives.Where(d => d.ElectronLedgerID == id.Value).ToArray();

                for(int i = 0; i < prod.Count(); i++)
                {
                    DBUtil.DeleteData(ref prog[i]);
                }

                var ba = db.BARepresentatives.Where(d => d.ElectronLedgerID == id.Value).ToArray();

                for(int i = 0; i < ba.Count(); i++)
                {
                    DBUtil.DeleteData(ref ba[i]);
                }

                var adv = db.AdvertisementValues.Where(d => d.ElectronLedgerID == id.Value).ToArray();

                for(int i = 0; i < adv.Count(); i++)
                {
                    DBUtil.DeleteData(ref adv[i]);
                }

                result = db.SaveChanges();
                if(result > 0)
                {
                    var ret = new
                    {
                        Date = DateTime.Now.ToString("s"),
                        Result = true,
                        Reason = "削除しました",
                    };

                    return Json(ret, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    var ret = new
                    {
                        Date = DateTime.Now.ToString("s"),
                        Result = false,
                        Reason = "削除に失敗しました",
                    };

                    return Json(ret, JsonRequestBehavior.AllowGet);
                }
            }
        }
        #endregion

        /// <summary>
        /// 雑誌台帳保存
        /// </summary>
        /// <returns></returns>
        /// 

        #region Đăng Ký
        public ActionResult RegistMagazineLedger()
        {
            bool ret;
            List<string> reason;

            //  JSONデータ読み込み
            Request.InputStream.Position = 0;

            var data = DynamicJson.Parse(Request.InputStream, Encoding.UTF8);

            //  正当性チェック
            if(!CheckValid(data, out reason))
             {
                var failed = new
                {
                    date = DateTime.Now.ToLongTimeString(),
                    result = false,
                    reason = reason,
                };

                return Json(failed, JsonRequestBehavior.AllowGet);
            }

            using(HMPZDDB db = new HMPZDDB())
            {
                try
                {
                    #region 台帳データ保存 //Lưu
                    ElectronLedger ledger;// = new ElectronLedger();

                    //  新規登録か編集かの違いはIDの有無で判別する
                    if(data.ID != null)
                    {
                        //  編集
                        int id = (int)data.ID;
                        ledger = db.ElectronLedger.FirstOrDefault(d => d.ID == id);
                    }
                    else
                    {
                        //  新規
                        ledger = new ElectronLedger();
                    }

                    ledger.Status = ValueUtil.ParseInt(data.Status);
                    ledger.Type = ValueUtil.ParseInt(data.Type);
                    ledger.IssuanceStatus = ValueUtil.ParseInt(data.IssuanceStatus);
                    ledger.IssuanceDate = ValueUtil.ToDateTime(data.IssuanceDate);
                    ledger.IssuanceUserName = ValueUtil.ToString(data.IssuanceUserName);
                    ledger.ReceptStatus = ValueUtil.ParseInt(data.ReceptStatus);
                    ledger.ReceptDate = ValueUtil.ToDateTime(data.ReceptDate);
                    ledger.ReceptUserName = ValueUtil.ToString(data.ReceptUserName);
                    ledger.BAOrderStatus = ValueUtil.ParseInt(data.BAOrderStatus);
                    ledger.BAOrderDate = ValueUtil.ToDateTime(data.BAOrderDate);
                    ledger.BAOrderUserName = ValueUtil.ToString(data.BAOrderUserName);
                    ledger.CustomerApplicationStatus = ValueUtil.ParseInt(data.CustomerApplicationStatus);
                    ledger.CustomerApplicationDate = ValueUtil.ToDateTime(data.CustomerApplicationDate);
                    ledger.CustomerApplicationUser = ValueUtil.ToString(data.CustomerApplicationUser);
                    ledger.SubmitReceptStatus = ValueUtil.ParseInt(data.SubmitReceptStatus);
                    ledger.SubmitReceptDate = ValueUtil.ToDateTime(data.SubmitReceptDate);
                    ledger.SubmitReceptUser = ValueUtil.ToString(data.SubmitReceptUser);

                    //  フリー入力が存在していたらフリーを優先する
                    if(string.IsNullOrEmpty(ValueUtil.ToString(data.CustomerFree)))
                    {
                        ledger.CustomerID = ValueUtil.ToString(data.CustomerID);
                    }
                    else
                    {
                        ledger.CustomerFree = ValueUtil.ToString(data.CustomerFree);
                    }

                    if(string.IsNullOrEmpty(ValueUtil.ToString(data.VehicleFree)))
                    {
                        ledger.VehicleID = ValueUtil.ParseInt(data.VehicleID);
                    }
                    else
                    {
                        ledger.VehicleFree = ValueUtil.ToString(data.VehicleFree);
                    }

                    if(string.IsNullOrEmpty(ValueUtil.ToString(data.OrderDestinationFree)))
                    {
                        ledger.OrderDestinationID = ValueUtil.ParseInt(data.OrderDestinationID);
                    }
                    else
                    {
                        ledger.OrderDestinationFree = ValueUtil.ToString(data.OrderDestinationFree);
                    }

                    ledger.ReleaseDate = ValueUtil.ToString(data.ReleaseDate);

                    //  発売日フラグ
                    #region ReleaseDateFlg
                    //  初期値として0を入れておく
                    ledger.ReleaseDateFlg = 0;

                    if(ledger.VehicleID != null)
                    {
                        //  進行スケジュールから媒体誌のスケジュールデータを取得
                        var sch = db.ProgressSchedules.FirstOrDefault(d => d.DeleteFlg != DBUtil.FLAG_YES &&
                                                                           d.VehicleID == ledger.VehicleID);

                        if(sch != null)
                        {

HMP-ZD/Controllers/Ledger/PopupMainController.cs
using HMP_ZD.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HMP_ZD.Controllers.Admin.Ledger
{
    public class PopupMainController : Controller
    {
        // GET: PopupMain
        public ActionResult Index()
        {
            var db = new HMPZDDB();

            // データ一式。JOINさせる
            
            return PartialView("~/Views/Shared/Ledger/Info_popup_Main.cshtml");
        }
    }
}

HMP-ZD/Views/Ledger/Top.cshtml
@{
    ViewBag.Title = "トップ";
    ViewBag.Header = HeaderMenu.Index;
}
<script src="~/Scripts/grid.js"></script>
<script src="~/Scripts/page/Top.js"></script>

<!-- <h1 class="ttl-h1">雑誌局電子台帳一覧</h1> -->
<ul class="btn-edit-list-top">
    <li><a class="btn-st btn-normal" href="@Url.Action("Index", "Magazine")">雑誌登録</a></li>
    <li><a class="btn-st btn-normal" href="@Url.Action("Index", "Web")">web登録</a></li>
    <li><a class="btn-st btn-normal" href="@Url.Action("New", "Work")">制作登録</a></li>
</ul>
<div id="menu-sort">
    <div id="menu-sort-btn">
        <span class="line line01"></span>
        <span class="line line02"></span>
        <span class="line line03"></span>
        <p>MENU</p>
    </div>
    <div id="menu-sort-list">
        <dl>            
            @* FIXME value はもう少し分かりやすいほうがよい *@
            <dt>表示列</dt>
            <dd><label><input type="radio" name="S_COLUMN" value="TEAM" />チーム別</label></dd>
            <dd><label><input type="radio" name="S_COLUMN" value="ADVERTISER" />広告主別</label></dd>
            <dd><label><input type="radio" name="S_COLUMN" value="PAYEE" />支払い先別</label></dd>
            <dt>表示行</dt>
            <dd><label><input type="checkbox" name="S_MAGAZINE" value="1" />雑誌</label></dd>
            <dd><label><input type="checkbox" name="S_WEB" value="1" />WEB</label></dd>
            <dd><label><input type="checkbox" name="S_PUBLICATION" value="1" />制作</label></dd>
        </dl>
    </div>
</div>
<div class="cotent-inner01 mt-20">
    <div class="jsGrid" style="width:1890px;height:546px;">
        @*
            <table class="tbl w-full highlight h-stripe-odd">
                <colgroup>
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                    <col style="width:130px;">
                </colgroup>
                <tr><th>項目名</th><th>項目名</th><th>項目名</th><th>項目名</th><th>項目名</th><th>項目名</th><th>項目名</th><th>項目名</th><th>項目名</th></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
                <tr><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
            </table>
        *@
    </div>
    <p class="mt-20">集計合計 000000</p>
    <div class="mt-10"><a class="btn-hk btn-normal" href="#">集計</a></div>
</div>
<div class="jsGridPager"></div>
<div class="popup">
    @Html.Partial("Ledger/Info_popup_Main")
</div>
<!--
<div class="pager">
    <ul>
        <li class="prev"><a href="#"><i class="fa fa-chevron-left"></i></a></li>
        <li class="num"><a href="#">1</a></li>
        <li><span>…</span></li>
        <li class="num"><a href="#">3</a></li>
        <li class="num"><a href="#">4</a></li>
        <li class="num current"><a href="#">5</a></li>
        <li class="num"><a href="#">6</a></li>
        <li class="num"><a href="#">7</a></li>
        <li><span>…</span></li>
        <li class="num"><a href="#">10</a></li>
        <li class="next"><a href="#"><i class="fa fa-chevron-right"></i></a></li>
    </ul>
</div> -->